# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-02 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('image_01', models.ImageField(blank=True, upload_to='images')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField(blank=True)),
                ('size', models.CharField(default='', max_length=100)),
                ('colour', models.CharField(default='', max_length=100)),
                ('flex', models.CharField(default='', max_length=100)),
                ('shape', models.CharField(default='', max_length=100)),
                ('board_profile', models.CharField(default='', max_length=100)),
                ('stock', models.IntegerField(blank=True)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
