# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-27 23:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snowboard_category', models.CharField(max_length=250, unique=True)),
                ('category_description', models.TextField(blank=True)),
                ('category_image', models.ImageField(blank=True, upload_to='category')),
                ('category_slug', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=250)),
                ('image_01', models.ImageField(blank=True, upload_to='images')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField(blank=True)),
                ('size', models.CharField(default='', max_length=100)),
                ('colour', models.CharField(default='', max_length=100)),
                ('gender', models.CharField(default='', max_length=100)),
                ('year', models.CharField(default='', max_length=100)),
                ('flex', models.CharField(default='', max_length=100)),
                ('shape', models.CharField(default='', max_length=100)),
                ('rider_profile', models.CharField(default='', max_length=100)),
                ('board_profile', models.CharField(default='', max_length=100)),
                ('condition', models.CharField(default='', max_length=100)),
                ('stock', models.IntegerField(blank=True)),
                ('available', models.BooleanField(default=True)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.Category')),
            ],
        ),
    ]
