# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-19 15:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200319_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_image_01',
            new_name='image_01',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_image_02',
            new_name='image_02',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_image_03',
            new_name='image_03',
        ),
    ]
