# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-24 18:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200319_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='board_proflie',
            new_name='board_profile',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='rider_prodile',
            new_name='rider_profile',
        ),
    ]
