# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-10 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200409_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='choice',
            field=models.CharField(choices=[('all_mountain', 'All Mountain'), ('big_mountain', 'Big Mountain'), ('freestyle', 'Freestyle'), ('pipe_park', 'Pipe/Park'), ('jib_street', 'Jib/Street'), ('boardercross', 'Boardercross'), ('accessory', 'Accessories')], default='All Mountain', max_length=50),
        ),
    ]
